swagger: "2.0"
basePath: /
schemes:
    - https
info:
  description: "The Upload Service is designed to ingest payloads from customers and distribute them via a message queue to other Platform services."
  version: 0.0.1
  title: Upload Service
  contact:
    email: sadams@redhat.com

paths:
  /:
    get:
      description: |
        Liveliness
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/MessageBody'
    options:
      description: |
        Add allowed methods header
      responses:
        200:
          description: OK
          headers:
            Allow:
              type: string
              description: 'GET, HEAD, OPTIONS'
  /v1/upload:
    get:
      description: |
        Display accepted content-type
      produces:
        - text/plain
      responses:
        200:
          description: "Accepted Content-Types: gzipped tarfile, zip file"
    post:
      description: |
        Handle uploaded files from customers
      responses:
        202:
          description: 'Accepted'
        415:
          description: 'Upload field not found'
        413:
          description: 'Payload too large'
    options:
      description: |
        Add allowed methods header
      responses:
        200:
          description: OK
          headers:
            Allow:
              type: string
              description: 'GET, POST, HEAD, OPTIONS'
  /v1/version:
    get:
      description: |
        Display API version
      produces:
        - application/json
      responses:
        200:
          description: OK

definitions:
  MessageBody:
    type: string
    example: boop
